name: MinewebBridge
main: fr.vmarchaud.mineweb.bukkit.BukkitCore
version: 2.0.0
author: ThisIsMac
commands:
  mineweb:
    description: Reset configuration
    usage: /mineweb reset
    permission: mineweb.reset